---
title: "About This Website"
bibliography: bibliography.bib
output: 
  html_document:
    css: style.css
    theme: cosmo
---

<!-- Google Analytics Script  -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-88888600-1', 'auto');
  ga('send', 'pageview');

</script>

<br>

This website hosts prototype tools built to expand on the <a href='http://www.dfo-mpo.gc.ca/csas-sccs/Publications/ResDocs-DocRech/2016/2016_002-eng.html'> Fish Swimming Performance Database and Analyses </a> CSAS document [@katopodis2016fish]. This website was coded by Richard Di Rocco with input from Richard Gervais. Feedback regarding these tools is welcome and can be submitted <a href='mailto:richard.dirocco@dfo-mpo.gc.ca'>here</a>.


## Citing this tool

Please cite the CSAS document and this website separately as:

Katopodis, C, and R Gervais. 2016. *Fish Swimming Performance Database and Analyses*. DFO Can. Sci. Advis. Sec. Res. Doc. 2016/002., 550. Available from http://www.dfo-mpo.gc.ca/csas-sccs/Publications/ResDocs-DocRech/2016/2016_002-eng.html.

Di Rocco, R, and R. Gervais. `r paste(format(Sys.Date(),"%Y"), ". ", sep="")`*SPOT: Swim Performance Online Tools*. Available from https://fishprotectiontools.ca/. 

## Packages

These tools are coded in <a href='https://www.r-project.org/' target='_blank'>R</a> [@R] using the following packages:

* <a href='https://shiny.rstudio.com/' target='_blank'> Shiny</a> [@shiny]
* <a href='http://ggplot2.tidyverse.org/' target='_blank'> ggplot2</a> [@ggplot2]
* <a href='http://ggvis.rstudio.com/' target='_blank'> ggvis</a> [@ggvis]
* <a href='http://tidyr.tidyverse.org/' target='_blank'> tidyr</a> [@tidyr]
* <a href='http://rmarkdown.rstudio.com/' target='_blank'>R Markdown</a> [@rmarkdown]
* <a href='https://github.com/ropensci/rfishbase' target='_blank'>rfishbase</a> [@rfishbase]

## References
<div id="refs"></div>

<br>
<br>

<center>
`r paste("Date Modified", Sys.Date())`
</center>

