---
title: "Manual: End-of-Pipe Screen Size Tool"
bibliography: bibliography.bib
output: 
  html_document:
    css: style.css
    theme: cosmo
---

<!-- Google Analytics Script -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-88888600-1', 'auto');
  ga('send', 'pageview');

</script>

##Background

<iframe src="https://player.vimeo.com/video/212965322" width="320" height="240" style="float:right;margin-left:10px"frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>

Water intakes without screens can entrain fish. The included video shows green sturgeon being entrained into a pipe which is withdrawing water at a rate of 570 L/s from an experimental channel [@mussen2014unscreened]. To prevent entrainment, a screen should be fitted to water intakes. If the screen area is too small, fish can become impinged on the screen. The [End-of-Pipe Screen Size tool](http://www.fishprotectiontools.ca/endofpipe-tool.html) is used to calculate the required Open Screen Area for a water intake pipe based on the fish species, their size, and the volume of water being withdrawn. <b>Open Screen Area</b> is the amount of area available for the free flow of water. It does not include the space obstructed by the screen mesh or any supports. This tool predicts fish swim performance using a model built on 27,030 individual fish found in 132 data sources. For details on the model, dataset and how these calculations are performed, see [Katopodis &amp; Gervais (2016)](http://www.dfo-mpo.gc.ca/csas-sccs/Publications/ResDocs-DocRech/2016/2016_002-eng.html). 



In this manual, a sample problem will be answered using this tool.

##Sample question

A proponent wishes to withdraw water at a rate of 90 L/s from a nearby pond. The pond supports populations of smallmouth bass, yellow perch, and northern pike. The intake is proposed to be cylindrical with the ends solid and #60 wedge wire screen around the cylinder. What size should the intake screen be?

###Steps

A.  Determine the required open screen area
B.  Determine the required total screen area
C.  Determine the dimensions of the screen

#### A. Determining open screen area

Complete these steps using the [End-of-Pipe Screen Size tool](http://www.fishprotectiontools.ca/endofpipe-tool.html)

1.	In the “Select fish by:” dropdown, choose “Group”.
2.	Below “Select groups:”, check the “Catfish & Sunfish”, "Pike" and “Salmon & Walleye” boxes.
3.	Enter "90" in the "Intake flow rate (L/s):" box. 

Once these steps are completed, the tool will indicate an Open Screen Area of 1.634 m^2^ is required. The tool should look like this:

<iframe id="nestedIFrame" src="http://www.fishprotectiontools.ca/endofpipe/?_inputs_&CatfishSunfish=true&Eel=false&EoP_CName=%22Brook%20trout%22&EoP_flowrate=90&EoP_l=25&EoP_Selecter=%220%22&EoP_SName=%22Salvelinus%20fontinalis%22&EoP_time=10&Herring=false&Pike=true&SalmonWalleye=true&Sturgeon=false" width="100%" frameBorder="0" scrolling="no"></iframe>

<!-- Load JS to automatically resize iframe depending on height of shiny app  -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script type="text/javascript" src="./JS/ie8.polyfils.min.js"></script>
<script type="text/javascript" src="./JS/iframeResizer.min.js"></script>
<script type="text/javascript">
   iFrameResize({heightCalculationMethod: "lowestElement"});
</script>

####B. Determine total screen area

The screen material in this case is # 60 Wedge Wire. A review of the end of pipe screen guideline indicates that the % Open Area for this material is 63%. With this value and the previously estimated Open Screen Area from Step A, the following formula is used to determine the Total Screen Area

$$
\begin{aligned}
  \text{Total Screen Area} &= \text{Open Screen Area} \div \left(\frac{\text{% Open Area}}{100}\right) \\
  &= 1.634 \text{ m}^2 \div \left(\frac{63}{100}\right) \\
  &= 2.594 \text{ m}^2
\end{aligned}
$$

####C. Determine dimensions of intake screen

For a cylindrical screen where the ends are solid and screening is around the cylinder, the following formula applies:

$$Area = \pi DL$$
The unknown dimensions are diameter (D) and length (L). These dimensions are determined by choosing a value for one and solving the equation for the other. If the diameter is 0.60 m, then the length follows as:

$$
\begin{aligned}
  2.594\text{ m}^2 &= \pi (0.60 \text{ m})L \\
  2.594\text{ m}^2 &= (1.885\text{ m})L \\
  L &= 2.594\text{ m}^2 \div 1.855 \text{ m} \\
  L &= 1.40\text{ m}^2
\end{aligned}
$$

###Solution

A regularly cleaned 0.60 m diameter, 1.40 m long cylindrical screen would meet the design requirements. It should be noted that the dimensions given are representative of the screening area only; they do not include any screen that may be blocked by framing, etc.

##Advanced options

Clicking the "Show advanced options"" check box allows for much more control than previously possible through the [1995 guideline](http://www.dfo-mpo.gc.ca/Library/223669.pdf), including the ability to change the amount of time required for a fish to escape the face of a screen, the ability to decrease the proportion of fish protected below 97.5%, and the ability to increase the length of fish near the water intake. In most scenarios, these values should not be changed from their default values.

##Additional information

Below the chart, a line of text displays the design approach velocity in m/s. This information may be useful when using the end-of-pipe screen size calculator in conjunction with provincial regulations or to verify the screen is working properly once installed. 

The end-of-pipe screen size tool can be used to calculate the open screen area needed to prevent most entrainment and impingement with no information other than the intake flow rate. To do this, ensure all groups are selected and the mode is set to "basic". Enter the intake flow and the open screen area will prevent nearly all fish larger than 25 mm from being entrained or impinged at that water intake. It is important to remember that these screens do little to protect plankton, such as early life-stage fish, from becoming entrained or impinged. 

### References