---
title: "Manual: Swim Speed & Swim Time Tool"
output: 
  html_document:
    css: style.css
    theme: cosmo
---

<!-- Google Analytics Script -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-88888600-1', 'auto');
  ga('send', 'pageview');

</script>

##Background

The ability to predict fish swim speed and stamina is helpful in the development and design of fish passage, exclusion, and guidance systems. The [Swim Speed &amp; Swim Time tool](http://www.fishprotectiontools.ca/speedtime.html) generates a plot showing swim speed versus swim time using a model built on 27,030 individual fish found in 132 data sources. For details on the model, dataset and how these calculations are performed, see [Katopodis &amp; Gervais (2016)](http://www.dfo-mpo.gc.ca/csas-sccs/Publications/ResDocs-DocRech/2016/2016_002-eng.pdf). The model calculates the mean swimming performance surrounded by 75% and 95% prediction intervals. These intervals show the expected range of swim performance values. For example, 95% of unsampled fish should fall within the bounds of the 95% prediction interval. 

In this manual, a sample problem will be answered using this tool.

##Question

How long can the average 250 mm rainbow trout swim 1 m/s?

##Steps


1. Go to the [Swim Speed &amp; Swim Time tool](http://www.fishprotectiontools.ca/speedtime.html).
2. Below "Select Fish by:", click the "Common name" radio button.
3. In the "Select species" drop down menu, choose "Rainbow or Steelhead trout".
4. Drag the "Fish length" slider to 250 mm.
5. Below "Calculations:" press the "Swim time" radio button.
6. Enter "1" in the "Swim speed" box.

Once these steps are completed, the tool should look like this:

<iframe id="nestedIFrame" src="http://www.fishprotectiontools.ca/speedtime/?_inputs_&Calculate=%222%22&CName=%22Rainbow%20or%20Steelhead%20trout%22&Group=%22Salmon%20%26%20Walleye%22&l=250&Selecter=%221%22&SName=%22Salvelinus%20fontinalis%22&SS=%221%22&SSEst=true&ST=%22600%22&STEst=true" width="100%" frameBorder="0" scrolling="no"></iframe>

<!-- Load JS to automatically resize iframe depending on height of shiny app  -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script type="text/javascript" src="./JS/ie8.polyfils.min.js"></script>
<script type="text/javascript" src="./JS/iframeResizer.min.js"></script>
<script type="text/javascript">
   iFrameResize({heightCalculationMethod: "lowestElement"});
</script>

##Solution

The average 250 mm rainbow trout can swim 1 m/s for 250 seconds. 

##Calculating swim speed

The tool can also be used to determine swim speed based on swim time. For example, select the "Swim speed" radio button below "Calculations" and enter 250 s into the "Swim time" box. The plot will update and show the average rainbow trout can swim 1 m/s for 250 s. 

##Manual calculations

The fish swimming performance models presented in [Katopodis &amp; Gervais (2016)](http://www.dfo-mpo.gc.ca/csas-sccs/Publications/ResDocs-DocRech/2016/2016_002-eng.pdf) are potentially useful but required solving complex equations. The web tool reliably and quickly performs these calculations, reducing the likelihood of an erroneous result. In this section, the simplified equations from the report are displayed for reference.

Fish swimming speed is calculated using the following formula:

$$U = kt^b \sqrt{gl}\left(\frac{l}{g}\right)^{-b/2}$$
Where:

*   *U* is the fish swimming speed in m/s
*   *t* is endurance time in seconds and is limited from 3 to 1800 seconds
*   *g* is gravitational acceleration (9.81 m/s^2^)
*   *l* is fish length in meters
*   *k* and *b* are coefficients derived from Deming regression analysis
    + These values can be found in [Katopodis &amp; Gervais (2016)](http://www.dfo-mpo.gc.ca/csas-sccs/Publications/ResDocs-DocRech/2016/2016_002-eng.pdf)
    
The formula can be rearranged to estimate time based on fish swimming speed:

$$t = \left(\frac{U(l/g)^{b/2}}{k \sqrt{gl}}\right) ^{1/b} $$

##Model limitations

Some fish swimming performance groups had limited data available. This lack of data for certain groups may affect the estimated performance. These limitations are outlined below: 

*   **Catfish & Sunfish**: Limited data on burst range
*   **Eel**: Comprehensive data set
*   **Herring**: Lack of prolonged data
*   **Salmon & Walleye**: Comprehensive data set
*   **Sturgeon**: Lack of burst data
*   **Pike**: Lack of burst data, curve derived by assuming burst performance is similar to Salmon & Walleye and Eel groups
